import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import {
  CONCURRENCY,
  FIRST_PHOTO,
  SETTLE_ATTEMPTS,
  SETTLE_WAIT_MS,
  SITE_FILES,
  SPACING_MS,
  TIMEOUT_MS,
  addressOf,
  inFlight,
  looksLike,
  verdictIsAlarming,
  verdictLine,
  verdictOf,
} from "./site-health.js";
import { LEVEL_PHOTOS } from "./level-images.js";
import { PREVIEW_FILE, ROBOTS_FILE, SITEMAP_FILE, siteOrigin } from "../../build/site-files.js";

// Whether the published site is still there.
//
// The application has no server to watch, and the way a static site fails is
// quiet: the address keeps answering, and what it answers with is the wrong
// thing. These tests are about telling those apart, since a check that only asks
// "does it reply?" would pass on a site that no longer exists.

const ROOT = path.resolve(import.meta.dirname, "..", "..");
const read = (file) => readFileSync(path.join(ROOT, file), "utf8");

test("the addresses checked are the files the build writes", () => {
  const paths = SITE_FILES.map((file) => file.path);
  assert.deepEqual(paths, [
    "",
    ROBOTS_FILE,
    SITEMAP_FILE,
    PREVIEW_FILE,
    // The four the build writes are served from the root of the site, where a
    // path cannot be wrong. What follows them is what moves when the site moves:
    // the page a deep link is answered with, the worker, a photograph, and a
    // page opened by its own address. Every one of them was missing from this
    // list the day the gallery came back empty on the published site.
    "404.html",
    "sw.js",
    FIRST_PHOTO,
    "PrivacyPolicy",
  ]);
  assert.equal(paths[0], "", "the landing page is the first thing checked");
  for (const file of SITE_FILES) {
    assert.ok(file.what && file.kind, `${file.path || "/"} says what it is`);
  }

  // The photograph is taken from the table the game ships, not written here: a
  // picture replaced is a picture this check follows.
  assert.equal(FIRST_PHOTO, `photos/${LEVEL_PHOTOS[0].file.split("/").pop().replace(/\.jpe?g$/, ".webp")}`);

  // Built from the one address in the repository, so the check cannot be pointed
  // at a site the application is not published at.
  assert.equal(addressOf("https://example.org/quest", ""), "https://example.org/quest/");
  assert.equal(addressOf("https://example.org/quest/", "robots.txt"), "https://example.org/quest/robots.txt");
  assert.equal(addressOf("https://example.org", "sitemap.xml"), "https://example.org/sitemap.xml");
  assert.ok(SITE_FILES.every((file) => addressOf(siteOrigin({}), file.path).startsWith("https://")));
});

test("each file is recognised by something it cannot be without", () => {
  // A real file of each kind, as the build writes it: the page the application
  // is mounted on, the crawler file, the sitemap, the signature of a PNG.
  const page = '<!doctype html><html><head><title>Africa History Quest</title></head><body><div id="root"></div>';
  const robots = "User-agent: *\nAllow: /\n\nSitemap: https://example.org/quest/sitemap.xml\n";
  const sitemap = '<?xml version="1.0"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://example.org/quest/</loc></url></urlset>';
  const picture = "\u0089PNG\r\n\u001a\n\u0000\u0000\u0000\rIHDR";

  const photo = "RIFF\u0034\u0000\u0000\u0000WEBPVP8 ";
  const worker =
    '// Generated by build/offline-plugin.js. Do not edit by hand.\nconst SHELL = ["/index.html","/assets/level-09-DY2Tac4I.js"];\n';
  const script = 'const react = {};\nexport { react };\n';

  assert.equal(looksLike("page", page), true);
  assert.equal(looksLike("robots", robots), true);
  assert.equal(looksLike("sitemap", sitemap), true);
  assert.equal(looksLike("picture", picture), true);
  assert.equal(looksLike("photo", photo), true);
  assert.equal(looksLike("worker", worker), true);
  assert.equal(looksLike("deeplink", page), true, "a deep link is the same page, answered again");
  assert.equal(looksLike("script", script), true);

  // And by something it must have: a page without the root element is not the
  // application, a crawler file without a sitemap line is an empty promise, a
  // sitemap without an address is a file rather than a list.
  assert.equal(looksLike("page", "<html><body>Not found</body></html>"), false);
  assert.equal(looksLike("robots", "User-agent: *\nDisallow: /\n"), false);
  assert.equal(looksLike("sitemap", "<html>Nothing here</html>"), false);
  assert.equal(looksLike("picture", "PNG"), false);
  assert.equal(looksLike("photo", "JFIF, a JPEG is not the light version"), false);
  assert.equal(looksLike("photo", page), false, "the application is not a picture");
  assert.equal(looksLike("worker", script), false, "a chunk is not the worker");
  assert.equal(looksLike("worker", worker.replace(/SHELL = \[[^\]]*\]/, "SHELL = []")), false, "a worker with nothing to install");
  assert.equal(looksLike("script", page), false, "the page answering for an asset that is not there");
  assert.equal(looksLike("script", ""), false, "an empty answer is not a script");
  assert.equal(looksLike("nothing-like-this", page), false);
});

test("a deep link is answered by the page, and the absence of it is not", () => {
  // Pages answers a path it does not have with 404.html and the status 404. That
  // is a site working: a reader opening a shared link to the privacy notice
  // meets the application rather than a page of the host's. Reading the status
  // alone would fail every run on a site that is doing exactly the right thing.
  const app = '<!doctype html><div id="root"></div><title>Africa History Quest</title>';
  assert.equal(verdictOf({ kind: "deeplink", status: 404, body: app }), "healthy");
  assert.equal(verdictOf({ kind: "deeplink", status: 200, body: app }), "healthy");

  // What it must not be: the host's own page, or a file that is not there.
  assert.equal(verdictOf({ kind: "deeplink", status: 404, body: "<h1>404 Not Found</h1>" }), "missing");
  assert.equal(verdictOf({ kind: "deeplink", status: 200, body: "<h1>Repository not found</h1>" }), "wrong");

  // And no other file is allowed to answer with a 404 for a page that is there.
  assert.equal(verdictOf({ kind: "page", status: 404, body: app }), "missing");
  assert.equal(verdictOf({ kind: "photo", status: 404, body: "" }), "missing");
});

test("the built worker is read after the build, not during the unit tests", () => {
  // This test used to read dist/sw.js itself, and it failed on every fresh
  // checkout: the unit tests run before the bundle, so a machine that had never
  // built had nothing to read, while a machine that had built once passed - the
  // worst kind of check, since it hides on the machine that wrote it. The built
  // worker is a step of its own now, after the build, and this holds the two ends
  // of that: the script is there, and the verification runs it after the bundle
  // that writes what it reads.
  const source = read("scripts/check-worker.mjs");
  assert.match(source, /dist[\s\S]{0,40}sw\.js/, "the check does not read the built worker");

  const verify = read("scripts/verify.mjs");
  const worker = verify.indexOf("scripts/check-worker.mjs");
  const build = verify.indexOf("vite.js");
  assert.ok(worker > 0, "the verification no longer reads the built worker");
  assert.ok(build > 0 && worker > build, "the worker is read before the build that writes it");
});

test("the bytes of a picture are read with the decoder that keeps them", () => {
  // Node labels TextDecoder("latin1") as windows-1252, where the byte 0x89 of a
  // PNG decodes to U+2030 rather than U+0089: the signature the check looks for
  // then never matches a real file, and the link preview is reported as wrong
  // however well it was published. Buffer's latin1 maps every byte to its own
  // character, and it is the one a picture is read with.
  const png = Buffer.from([
    0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d, 0x49, 0x48, 0x44, 0x52,
  ]);
  assert.equal(looksLike("picture", png.toString("latin1")), true, "a real PNG is recognised");
  assert.equal(
    looksLike("picture", new TextDecoder("latin1").decode(png)),
    false,
    "and the platform's latin1 is not the decoder that keeps the bytes"
  );
  assert.match(
    read("scripts/check-site.mjs"),
    /toString\("latin1"\)/,
    "the check reads a picture through the platform decoder again"
  );
});

test("what an answer means is not the same question as whether it answered", () => {
  const page = { kind: "page" };
  const good = { status: 200, body: '<div id="root"></div><title>Africa History Quest</title>' };

  assert.equal(verdictOf({ ...page, ...good }), "healthy");
  assert.equal(verdictIsAlarming("healthy"), false);

  // A file that is not there, and the two ways a host says so.
  assert.equal(verdictOf({ ...page, status: 404, body: "Not Found" }), "missing");
  assert.equal(verdictOf({ ...page, status: 410, body: "Gone" }), "missing");

  // The half published site, which is the failure this check exists for: a
  // success status, and the application itself where another file should be.
  const wrong = verdictOf({ ...page, status: 200, body: good.body });
  assert.equal(wrong, "healthy");
  assert.equal(verdictOf({ kind: "robots", status: 200, body: good.body }), "wrong");
  assert.equal(verdictOf({ kind: "picture", status: 200, body: good.body }), "wrong");
  assert.equal(verdictIsAlarming("wrong"), true);

  // A refusal that is neither a success nor a "not here": a deployment in
  // flight, or a host that has something to say about the request.
  for (const status of [301, 403, 429, 500, 502, 503]) {
    assert.equal(verdictOf({ ...page, status, body: "" }), "refused", `status ${status}`);
  }

  // And the answer that says nothing at all about the site.
  assert.equal(verdictOf({ ...page, error: new Error("ETIMEDOUT") }), "unreachable");
  assert.equal(verdictOf({ ...page, status: 0, body: "" }), "unreachable");

  // Every verdict reads as a sentence, in one line, naming the address.
  for (const verdict of ["healthy", "missing", "refused", "unreachable", "wrong"]) {
    const line = verdictLine(SITE_FILES[1], verdict);
    assert.match(line, /^\/robots\.txt \(the crawler file\) /);
    assert.ok(line.length < 120, line);
  }
});

test("a site that answers nothing is waited out, and a broken one is not", () => {
  // A deployment in flight and a site that is gone answer alike for a minute or
  // two: until the new deployment is published, Pages serves a 404 for every
  // address, which is what a repository whose Pages setting was turned off says
  // as well. So a read in which nothing arrived is made again; anything that did
  // arrive is the failure this check exists for, and is decided at once.
  const gone = SITE_FILES.map((file) => ({ kind: file.kind, status: 404, body: "" }));
  assert.equal(inFlight(gone), true, "a site that answers nothing is waited out");

  const unreachable = SITE_FILES.map((file) => ({ kind: file.kind, status: 0, body: "" }));
  assert.equal(inFlight(unreachable), true, "a host that does not answer is waited out too");

  // One address up means the site is up: what is missing beside it is a fault of
  // the deployment that put it there, not a deployment still in flight.
  const oneUp = [
    { kind: "page", status: 200, body: '<div id="root"></div><title>Africa History Quest</title>' },
    ...gone.slice(1),
  ];
  assert.equal(inFlight(oneUp), false, "a site that is there is not waited out");

  // And something that arrived with the wrong content is exactly what this check
  // must catch rather than sleep through.
  const wrong = [{ kind: "page", status: 200, body: "<h1>Not found</h1>" }, ...gone.slice(1)];
  assert.equal(inFlight(wrong), false, "a site answering with the wrong content is not waited out");

  // Nothing checked says nothing about the site, and is not a state to wait out.
  assert.equal(inFlight([]), false);
  assert.equal(inFlight(undefined), false);
});

test("the check is asked for, paced, and stays out of the verification", () => {
  const { scripts } = JSON.parse(read("package.json"));
  assert.match(scripts["check:site"], /check-site\.mjs/, "package.json registers the site check");
  assert.ok(!scripts.verify.includes("check-site"), "the verification needs no network");

  const script = read("scripts/check-site.mjs");
  // The address is the one the build writes, from the same module: one address
  // in this repository rather than three that can disagree.
  assert.match(script, /siteOrigin/, "the check invents its own address");
  // What was fetched is handed to the verdict with its kind beside the entry.
  // The verdict reads the answer and not the request, so an answer carrying no
  // kind is a file recognised by nothing: the script once passed the entry
  // alone, and every healthy file came back as "wrong" the day the site was
  // first published and answered with the content it should have.
  assert.match(script, /kind: entry\.kind,/, "the verdict is not told what it is looking at");
  assert.match(script, /SITE_FILES/, "the check no longer follows the list the tests read");
  assert.match(script, /site-health\.js/, "the verdicts are not the ones the tests read");
  // The second pass: the worker is read, and the addresses it names are asked
  // for in turn. Without it, nothing in this file looked at a built asset, and a
  // site whose chunks are published under another path passed the check.
  assert.match(script, /precachedFrom\(worker\.body\)/, "the worker is never read for its assets");
  assert.match(script, /chosenScripts\(/, "and the assets it names are never asked for");
  // A refusal is not read as a verdict of its own: only four files are asked
  // for, four at a time, spread out, with a timeout on each.
  assert.ok(CONCURRENCY <= 4 && SPACING_MS >= 100 && TIMEOUT_MS >= 5000, "the pacing is a flood");

  // And a site that answered nothing is read again before it is believed, which
  // is a wait in this script and not a softer verdict: the same alarming answer
  // is what a site that is really gone still ends on.
  assert.match(script, /inFlight\(/, "the check never waits for a deployment in flight");
  assert.ok(SETTLE_ATTEMPTS >= 2 && SETTLE_ATTEMPTS <= 5, "the site is read too few or too many times");
  assert.ok(SETTLE_WAIT_MS >= 5000 && SETTLE_WAIT_MS <= 120000, "the wait is not a wait, or it is a day");

  // And a failing run is what tells the publisher: GitHub notifies the owner of
  // a scheduled workflow that failed, which is why no third party watches this.
  const uptime = read(".github/workflows/uptime.yml");
  assert.match(uptime, /^name: Uptime$/m);
  assert.match(uptime, /schedule:/, "the check never runs by itself");
  assert.match(uptime, /cron: "\d+ \d+ \* \* \*"/, "the schedule is not a daily one");
  assert.match(uptime, /node scripts\/check-site\.mjs/);
  assert.match(uptime, /workflow_dispatch/, "the check cannot be asked for by hand");
  assert.doesNotMatch(uptime, /continue-on-error/, "a failed check is ignored");
});
