import { useState, useRef, useEffect } from "react";
import { VolumeX, Loader2, Play, Pause, Mic } from "lucide-react";
import { useLang, useT } from "../i18n";

// Short story/intro per level id
export const LEVEL_STORIES = {
  1: {
    en: "Around five thousand years ago, along the Nile in North Africa, a civilization rose that would last for three thousand years. Its people built the pyramids at Giza, wrote in hieroglyphs, and were ruled by kings called pharaohs. The river flooded every year and gave the fields their harvest, and the state that grew around it organised labour, writing and trade as few others had. Scribes kept the accounts, priests served the temples, and the pyramids were raised by farmers who worked between the harvest and the flood. The country called itself Kemet, the black land, after the soil the river left behind. Its ideas about the afterlife travelled far beyond the Nile, and when Cleopatra VII died in 30 BC Egypt became a province of Rome.",
    fr: "Il y a environ cinq mille ans, le long du Nil en Afrique du Nord, une civilisation est née qui allait durer trois mille ans. Ses habitants ont bâti les pyramides de Gizeh, écrit en hiéroglyphes, et étaient gouvernés par des rois appelés pharaons. Le fleuve débordait chaque année et donnait la récolte aux champs, et l'État qui s'est construit autour de lui a organisé le travail, l'écriture et le commerce comme peu d'autres. Les scribes tenaient les comptes, les prêtres servaient les temples, et les pyramides ont été élevées par des paysans qui travaillaient entre la récolte et la crue. Le pays s'appelait Kemet, la terre noire, d'après le limon laissé par le fleuve. Ses idées sur l'au-delà ont voyagé bien au-delà du Nil, et quand Cléopâtre VII est morte en 30 av. J.-C., l'Égypte est devenue une province romaine."
  },
  2: {
    en: "South of Egypt, in what is today Sudan, the kingdom of Kush grew strong on the third cataract of the Nile. Its kings ruled Egypt for about a century as the twenty-fifth dynasty, and its queens, the Kandakes, led armies themselves. The older capital was Napata, below the holy mountain of Jebel Barkal, and the kings were buried in steep pyramids at El-Kurru and Nuri. Later the court moved south to Meroe, where the kingdom worked iron, traded gold, and wrote in a script of its own that scholars can read by sound but not yet translate. In the fourth century the kingdom was worn down by Axum and by the desert, and three Christian Nubian kingdoms took its place along the river.",
    fr: "Au sud de l'Égypte, dans l'actuel Soudan, le royaume de Koush s'est renforcé sur la troisième cataracte du Nil. Ses rois ont gouverné l'Égypte pendant environ un siècle, comme vingt-cinquième dynastie, et ses reines, les Kandakés, commandaient elles-mêmes les armées. La première capitale était Napata, sous la montagne sainte du Djebel Barkal, et les rois étaient enterrés dans des pyramides à pentes raides, à El-Kourrou et à Nouri. La cour s'est ensuite installée plus au sud, à Méroé, où le royaume travaillait le fer, commerçait l'or et écrivait dans une écriture à lui que les savants lisent par le son sans pouvoir encore la traduire. Au IVe siècle, le royaume a été usé par Axoum et par le désert, et trois royaumes chrétiens nubiens ont pris sa place le long du fleuve."
  },
  3: {
    en: "Between the eleventh and fifteenth centuries, in the granite hills of southern Africa, a stone city rose that traded gold and ivory as far as the Swahili coast and beyond. Its walls were built of blocks cut to fit together without mortar, and the Great Enclosure still stands. Great Zimbabwe was the capital of a state that held the gold routes of the interior, and its merchants were paid in glass beads, porcelain and cloth carried up from the Indian Ocean. The kings lived on the Hill Complex, and the court and its chief ceremonies were held in the valley below. At its height more than eighteen thousand people lived in and around the city. Too many cattle and too many fields wore out the land, and when the gold trade moved north in the fifteenth century the court moved with it.",
    fr: "Entre le XIe et le XVe siècle, dans les collines de granite de l'Afrique australe, une cité de pierre s'est élevée, qui commerçait l'or et l'ivoire jusqu'à la côte swahili et au-delà. Ses murs sont faits de blocs taillés pour s'emboîter sans mortier, et la Grande Enceinte tient encore debout. Le Grand Zimbabwe était la capitale d'un État qui contrôlait les routes de l'or de l'intérieur, et ses marchands étaient payés en perles de verre, en porcelaine et en tissus remontés de l'océan Indien. Les rois vivaient sur le complexe de la colline, et la cour et ses grandes cérémonies se tenaient dans la vallée en contrebas. À son apogée, plus de dix-huit mille personnes vivaient dans la cité et autour d'elle. Trop de bétail et trop de champs ont épuisé la terre, et quand le commerce de l'or s'est déplacé vers le nord au XVe siècle, la cour a suivi."
  },
  4: {
    en: "In the thirteenth century, Sundiata Keita united the Mandinka kingdoms and founded an empire that reached from the Atlantic to the bend of the Niger. Its wealth came from gold and salt, and its cities, above all Timbuktu and Djenne, became centres of learning. Mansa Musa, who ruled in the fourteenth century, is remembered for his pilgrimage to Mecca and for the scholars who came with him on the way back. He took so much gold with him that its price in Cairo fell for years. At Timbuktu the students of Sankore came from across the western Sudan, and the books copied there were bought and sold in the market. After the death of its strongest kings the subject peoples broke away one by one, until Songhai took the trade and the cities.",
    fr: "Au XIIIe siècle, Soundjata Keïta a unifié les royaumes mandingues et fondé un empire qui allait de l'Atlantique à la boucle du Niger. Sa richesse venait de l'or et du sel, et ses villes, Tombouctou et Djenné au premier rang, sont devenues des centres de savoir. Mansa Moussa, qui a régné au XIVe siècle, reste connu pour son pèlerinage à La Mecque et pour les savants qui l'ont accompagné au retour. Il emportait tant d'or que son prix a baissé au Caire pendant des années. À Tombouctou, les étudiants de Sankoré venaient de tout le Soudan occidental, et les livres copiés sur place s'achetaient et se vendaient au marché. Après la mort de ses rois les plus forts, les peuples soumis se sont détachés l'un après l'autre, jusqu'à ce que le Songhaï prenne le commerce et les villes."
  },
  5: {
    en: "In the highlands of what are now Ethiopia and Eritrea, the kingdom of Axum grew rich on the trade of the Red Sea. It minted its own coins, raised obelisks cut from single blocks of stone, and adopted Christianity in the fourth century, among the first states in the world to do so. Its ships carried ivory, gold and incense to Rome, India and Arabia. The port of Adulis took the goods of the interior down to the sea, and a handbook written for merchants lists what was bought and sold there. Axum ruled part of southern Arabia for a few decades, and the script its kings used grew into the Ge'ez writing of Ethiopia. When Islam spread along the Red Sea in the seventh century the trade slipped away, and the centre of power moved south into the highlands.",
    fr: "Dans les hauts plateaux de l'actuelle Éthiopie et de l'Érythrée, le royaume d'Axoum s'est enrichi par le commerce de la mer Rouge. Il a frappé sa propre monnaie, dressé des obélisques taillés dans un seul bloc de pierre, et adopté le christianisme au IVe siècle, parmi les premiers États du monde à le faire. Ses navires portaient ivoire, or et encens vers Rome, l'Inde et l'Arabie. Le port d'Adoulis descendait les marchandises de l'intérieur vers la mer, et un manuel écrit pour les marchands énumère ce qu'on y achetait et y vendait. Axoum a gouverné une partie du sud de l'Arabie pendant quelques décennies, et l'écriture de ses rois est devenue le guèze d'Éthiopie. Quand l'islam s'est répandu le long de la mer Rouge au VIIe siècle, le commerce a glissé loin du royaume, et le centre du pouvoir s'est déplacé vers le sud, dans les hauts plateaux."
  },
  6: {
    en: "The largest empire in African history grew along the great bend of the Niger. Under Askia Muhammad, who took the throne in 1493, Songhai held Timbuktu and Djenne, taxed the salt caravans of the Sahara, and kept courts where jurists wrote and argued. The army that held it was made of cavalry, infantry and a fleet of river boats, and the boats counted as much as the horses. Timbuktu's scholars wrote on law, astronomy, medicine and history, and their manuscripts are still kept in the city today. In 1591 a Moroccan army armed with firearms broke the Songhai cavalry at Tondibi, and the empire came apart within a generation.",
    fr: "Le plus grand empire de l'histoire africaine s'est développé le long de la boucle du Niger. Sous Askia Muhammad, monté sur le trône en 1493, l'Empire songhaï tenait Tombouctou et Djenné, taxait les caravanes de sel du Sahara et entretenait des cours où les juristes écrivaient et discutaient. L'armée qui le tenait mêlait cavalerie, infanterie et une flotte de bateaux fluviaux, et les bateaux comptaient autant que les chevaux. Les lettrés de Tombouctou écrivaient sur le droit, l'astronomie, la médecine et l'histoire, et leurs manuscrits sont encore conservés dans la ville aujourd'hui. En 1591, une armée marocaine armée de fusils a brisé la cavalerie songhaï à Tondibi, et l'empire s'est disloqué en une génération."
  },
  7: {
    en: "In the hills of what is now KwaZulu-Natal, a young chief named Shaka turned a small clan into a kingdom in the early nineteenth century. He organised the army by age, shortened the spear for close fighting, and had the regiments live in royal towns. The amabutho, the age regiments, were the nation in arms: young men served in them before they could marry, and the king held the cattle and the land in trust for all. After Shaka died in 1828 the kingdom held its ground against Boer trekkers and then British columns. Cetshwayo's army destroyed a British camp at Isandlwana in 1879, but the kingdom could not replace what it lost, and Ulundi was burnt the same year. Zululand was divided, then annexed, and its name survives in the province of KwaZulu-Natal.",
    fr: "Dans les collines de l'actuel KwaZulu-Natal, un jeune chef nommé Shaka a transformé un petit clan en royaume au début du XIXe siècle. Il a organisé l'armée par classes d'âge, raccourci la lance pour le combat rapproché et installé les régiments dans des villes royales. Les amabutho, les régiments d'âge, étaient la nation en armes : les jeunes hommes y servaient avant de pouvoir se marier, et le roi détenait le bétail et la terre pour tous. Après la mort de Shaka en 1828, le royaume a tenu tête aux trekboers puis aux colonnes britanniques. L'armée de Cetshwayo a détruit un camp britannique à Isandlwana en 1879, mais le royaume ne pouvait pas remplacer ses pertes, et Ulundi a été brûlé la même année. Le Zoulouland a été partagé, puis annexé, et son nom survit dans la province du KwaZulu-Natal."
  },
  8: {
    en: "After the Second World War, the demand for independence spread across the continent. Ghana won it in 1957, the first country in West Africa to do so, and seventeen African states became independent in 1960 alone. Algeria won its independence in 1962 after eight years of war, Kenya in 1963, and the Portuguese colonies in 1975 after long armed struggles. Namibia became independent in 1990 and South Sudan in 2011, which is how long the whole process lasted. The decades that followed were not simple: the borders, the economies and the institutions all came out of colonial rule, and the new states had to build themselves from there.",
    fr: "Après la Seconde Guerre mondiale, l'exigence d'indépendance s'est répandue sur tout le continent. Le Ghana l'a obtenue en 1957, le premier pays d'Afrique de l'Ouest à y parvenir, et dix-sept États africains sont devenus indépendants en 1960 seulement. L'Algérie a gagné la sienne en 1962 après huit ans de guerre, le Kenya en 1963, et les colonies portugaises en 1975 après de longues luttes armées. La Namibie est devenue indépendante en 1990 et le Soudan du Sud en 2011 : c'est la durée totale du processus. Les décennies qui ont suivi n'ont pas été simples : les frontières, les économies et les institutions venaient toutes de la domination coloniale, et les nouveaux États ont dû se construire à partir de là."
  },
  9: {
    en: "Every human being alive today belongs to a species that was born in Africa. More than 300,000 years ago, our ancestors lived across the whole continent, from the hills of Morocco to the Ethiopian rift valley. They knapped stone, painted on rock, and buried their dead with care. The oldest known fossils of our own species come from Jebel Irhoud in Morocco, and the earliest stone tools from the shores of Lake Turkana. Hand axes of the Acheulean kind were made here for more than a million years before anyone thought of farming. Long before any kingdom existed, Africa was already carrying the entire human story.",
    fr: "Tous les êtres humains vivants appartiennent à une espèce née en Afrique. Il y a plus de 300 000 ans, nos ancêtres vivaient sur tout le continent, des collines du Maroc à la vallée du Rift éthiopien. Ils taillaient la pierre, peignaient sur la roche et enterraient leurs morts avec soin. Les plus anciens fossiles connus de notre espèce viennent de Jebel Irhoud, au Maroc, et les plus anciens outils de pierre des rives du lac Turkana. On y a fabriqué des bifaces acheuléens pendant plus d'un million d'années avant que quiconque songe à cultiver la terre. Bien avant le premier royaume, l'Afrique portait déjà toute l'histoire humaine."
  },
  10: {
    en: "On the coast of what is now Tunisia, Phoenician sailors founded a city that would challenge Rome for the mastery of the Mediterranean. Carthage built a trading empire, sent Hannibal over the Alps with elephants, and ruled the sea for centuries. Its two harbours, one for the merchants and one ringed basin for the warships, were cut by hand, and its estates grew the olives and the grain that paid for its fleets. Beyond the city lay the Berber kingdoms of Numidia, whose kings and writers, and one emperor, left their mark on Rome itself. Rome destroyed Carthage in 146 BC and made the land its province of Africa, whose harvest fed the capital for centuries.",
    fr: "Sur la côte de l'actuelle Tunisie, des marins phéniciens ont fondé une ville qui allait disputer à Rome la maîtrise de la Méditerranée. Carthage a bâti un empire commerçant, envoyé Hannibal franchir les Alpes avec des éléphants et régné sur la mer pendant des siècles. Ses deux ports, l'un pour les marchands et l'autre, en anneaux, pour les navires de guerre, étaient creusés à la main, et ses domaines produisaient l'huile et le blé qui payaient ses flottes. Au-delà s'étendaient les royaumes berbères de Numidie, dont les rois, les écrivains et un empereur ont marqué Rome elle-même. Rome a détruit Carthage en 146 av. J.-C. et a fait de la région sa province d'Afrique, dont la récolte a nourri la capitale pendant des siècles."
  },
  11: {
    en: "Around three thousand years ago, farmers in the borderlands of Nigeria and Cameroon began to move. They carried iron tools, seed crops and their languages, and over two thousand years their descendants settled from the Great Lakes to the Cape. In central Nigeria, the Nok artists modelled heads of astonishing size and detail in clay. Iron made the difference: an axe that would clear woodland, a hoe that would break new soil, and a spear for hunting and for war. The Bantu languages travelled with the farmers, which is why more than three hundred million people speak one today. Where the farmers met hunter-gatherers such as the San or the Mbuti the two ways of life traded and borrowed from each other, and the farmers crossed the great rainforest before they could reach the south.",
    fr: "Il y a environ trois mille ans, des agriculteurs des confins du Nigeria et du Cameroun se sont mis en marche. Ils emportaient des outils de fer, des semences et leurs langues, et en deux mille ans leurs descendants se sont installés des Grands Lacs jusqu'au Cap. Au centre du Nigeria, les artistes nok ont modelé dans l'argile des têtes d'une taille et d'une finesse surprenantes. Le fer a fait la différence : une hache pour défricher la forêt, une houe pour ouvrir une terre nouvelle, et une lance pour la chasse comme pour la guerre. Les langues bantoues ont voyagé avec les agriculteurs, et c'est pourquoi plus de trois cents millions de personnes en parlent une aujourd'hui. Là où ils ont rencontré des chasseurs-cueilleurs comme les San ou les Mbuti, les deux façons de vivre ont commerçé et emprunté l'une à l'autre, et les agriculteurs ont traversé la grande forêt avant d'atteindre le sud."
  },
  12: {
    en: "While much of Europe was rebuilding, a Christian kingdom in the Ethiopian highlands was carving churches into solid rock. The Zagwe kings cut the eleven churches of Lalibela downwards, so that each one rises from the ground like a planted cathedral. Then the Solomonic dynasty took the throne in 1270 and ruled for more than six centuries. The highlands traded with the Red Sea through Massawa, and caravans carried coffee, ivory and gold down to the coast. The church owned much of the land, ran the schools where Ge'ez was read and copied, and crowned the emperors at Axum. When an army from the sultanate of Adal almost destroyed the kingdom in the 1530s, Ethiopia fought back and kept its own script, its own church and its own history.",
    fr: "Alors qu'une grande partie de l'Europe se reconstruisait, un royaume chrétien des hauts plateaux éthiopiens creusait des églises dans la roche massive. Les rois zagwé ont taillé vers le bas les onze églises de Lalibela, si bien que chacune sort de terre comme une cathédrale plantée. Puis la dynastie salomonide a pris le trône en 1270 et a régné plus de six siècles. Les hauts plateaux commerçaient avec la mer Rouge par Massawa, et les caravanes descendaient le café, l'ivoire et l'or jusqu'à la côte. L'Église possédait une grande partie des terres, tenait les écoles où l'on lisait et copiait le guèze, et couronnait les empereurs à Axoum. Quand une armée du sultanat d'Adal a failli détruire le royaume dans les années 1530, l'Éthiopie a résisté et a gardé son écriture, son Église et son histoire."
  },
  13: {
    en: "In the western Sahel, a kingdom grew rich on two things everybody needed: gold and salt. Caravans carried Saharan salt south and forest gold north, and Ghana taxed every load. Its capital, Koumbi Saleh, had a royal town and a merchant town, and Arab geographers described its court with wonder. The king himself was called Ghana, and his title gave the empire its name. He kept the gold nuggets for himself and let the merchants deal in dust, so that the price never fell, and the trade up from the forests was carried on in silence. The Soninke farmers of Wagadu grew millet and sorghum on the edge of the desert. When the Almoravids sacked the capital in 1076, the empire began to fade, and Mali rose in its place.",
    fr: "Dans le Sahel occidental, un royaume s'est enrichi grâce à deux produits dont tout le monde avait besoin : l'or et le sel. Les caravanes descendaient le sel du Sahara vers le sud et remontaient l'or des forêts vers le nord, et le Ghana taxait chaque charge. Sa capitale, Koumbi Saleh, comptait une ville royale et une ville marchande, et les géographes arabes décrivaient sa cour avec admiration. Le roi lui-même portait le titre de Ghana, qui a donné son nom à l'empire. Il gardait les pépites pour lui et laissait aux marchands la poudre d'or, pour que le prix ne baisse jamais, et le commerce venu des forêts se faisait sans qu'un mot soit dit. Les paysans soninké du Wagadou cultivaient le mil et le sorgho à la lisière du désert. Quand les Almoravides ont pillé la capitale en 1076, l'empire a commencé à s'effacer, et le Mali a pris sa place."
  },
  14: {
    en: "South of the Sahara and west of the Nile, two worlds met: the grasslands around Lake Chad and the caravan routes to the Mediterranean. Kanem-Bornu ruled that meeting place for about a thousand years, from the Sayfawa dynasty to the musketeers of Idris Alooma. The kings took the title mai, and their dynasty lasted longer than almost any other in African history. Idris Alooma bought his muskets through the Ottoman empire and trained a corps of riflemen, and a chronicle written at his own court describes his wars and his reforms. To the west, the walled cities of the Hausa traded cloth, leather, horses and books behind earthen walls with gates, and several of their markets still open today.",
    fr: "Au sud du Sahara et à l'ouest du Nil, deux mondes se rencontraient : les savanes autour du lac Tchad et les routes caravanières vers la Méditerranée. Kanem-Bornou a gouverné ce carrefour pendant environ mille ans, de la dynastie sayfawa aux mousquetaires d'Idriss Alooma. Les rois portaient le titre de maï, et leur dynastie a duré plus longtemps que presque toute autre de l'histoire africaine. Idriss Alooma achetait ses mousquets par l'Empire ottoman et entraînait un corps de fusiliers, et une chronique écrite à sa propre cour décrit ses guerres et ses réformes. À l'ouest, les cités fortifiées haoussa commerçaient tissus, cuir, chevaux et livres derrière des murs de terre percés de portes, et plusieurs de leurs marchés s'ouvrent encore aujourd'hui."
  },
  15: {
    en: "The monsoon blew the dhows south in one season and north in the other, and along that rhythm a string of ports grew on the East African coast. Kilwa traded the gold of the interior for Chinese porcelain and Persian pottery, and Ibn Battuta called it one of the finest towns in the world. Each town had its sultan, its great mosque and its houses built from coral lime, and each one answered to the same winds, the same language and the same faith. Gold came down from the Zimbabwe plateau to Sofala, and the dhows carried it to Arabia, India and China, where a fleet under the admiral Zheng He reached the coast in the fifteenth century. The Swahili spoke a Bantu language, wrote it in Arabic script, and built a shared culture that still defines the coast.",
    fr: "La mousson poussait les boutres vers le sud pendant une saison et vers le nord pendant l'autre, et sur ce rythme une chaîne de ports a grandi sur la côte est-africaine. Kilwa échangeait l'or de l'intérieur contre de la porcelaine chinoise et de la poterie perse, et Ibn Battuta l'a décrite comme l'une des plus belles villes du monde. Chaque ville avait son sultan, sa grande mosquée et ses maisons liées au corail, et chacune répondait aux mêmes vents, à la même langue et à la même foi. L'or descendait du plateau du Zimbabwe vers Sofala, et les boutres le portaient en Arabie, en Inde et en Chine, où une flotte commandée par l'amiral Zheng He a atteint la côte au XVe siècle. Les Swahili parlaient une langue bantoue, l'écrivaient en caractères arabes et ont bâti une culture commune qui définit encore la côte."
  },
  16: {
    en: "Behind the Atlantic coast, in the forests and the savannah beyond them, some of the most remarkable states of Africa took shape. The Kongo kings wrote to Lisbon as equals, and the prophetess Kimpa Vita called her people to unity. In Benin, brass casters produced the plaques and heads that British troops would loot in 1897. In Ife, artists modelled faces of a calm and startling realism, and the horsemen of Oyo held the savannah for centuries. Each of these states governed by its own custom: the manikongo through governors and a council of nobles, the oba of Benin through the guilds of a great city, and the alaafin of Oyo through a council of chiefs that could check him. Further south the Kuba embroidered raffia cloth so finely that a single piece could take a year, and the Lunda empire traded copper and salt out of the savannah.",
    fr: "Derrière la côte atlantique, dans les forêts et les savanes qui les prolongent, quelques-uns des États les plus remarquables d'Afrique ont pris forme. Les rois du Kongo écrivaient à Lisbonne d'égal à égal, et la prophétesse Kimpa Vita appelait son peuple à l'unité. Au Bénin, les fondeurs de laiton ont produit les plaques et les têtes que les troupes britanniques allaient piller en 1897. À Ifé, les artistes modelaient des visages d'un réalisme calme et saisissant, et les cavaliers d'Oyo ont tenu la savane pendant des siècles. Chacun de ces États gouvernait selon sa propre coutume : le manikongo par des gouverneurs et un conseil de nobles, l'oba du Bénin par les corporations d'une grande ville, et l'alaafin d'Oyo par un conseil de chefs qui pouvait le contrôler. Plus au sud, les Kouba brodaient le raphia si finement qu'une seule pièce pouvait demander un an, et l'empire lounda commerçait le cuivre et le sel de la savane."
  },
  17: {
    en: "For more than three centuries, ships carried Africans across the Atlantic against their will. Roughly 12.5 million people were put on board, and about 10.7 million reached the Americas alive. Behind them they left villages emptied, ahead of them slavery. Yet the trade was resisted at every step, by kings who wrote to Lisbon, by uprisings at sea and on land, by writers such as Olaudah Equiano, and finally by the abolitionists who ended it. Kings in Kongo, Angola and Dahomey wrote to Europe to protest, and some of them lost their kingdoms for it. Captives seized ships, as on the Amistad in 1839, and communities of escaped people, the Maroons of Jamaica among them, held their own ground for generations. Brazil took more captives than any other country and was the last in the Americas to abolish slavery. The profits of the trade built ports and banks in Europe, and its memory is a road of departure, a door of no return, and a debate about what is owed.",
    fr: "Pendant plus de trois siècles, des navires ont transporté des Africains à travers l'Atlantique contre leur volonté. Environ 12,5 millions de personnes ont été embarquées, et environ 10,7 millions ont atteint les Amériques vivantes. Derrière elles, des villages vidés ; devant elles, l'esclavage. Pourtant la traite a été combattue à chaque étape, par des rois qui écrivaient à Lisbonne, par des révoltes en mer et sur terre, par des auteurs comme Olaudah Equiano, et enfin par les abolitionnistes qui l'ont fait cesser. Des rois du Kongo, d'Angola et du Dahomey ont écrit à l'Europe pour protester, et certains y ont perdu leur royaume. Des captifs se sont emparés de navires, comme sur l'Amistad en 1839, et des communautés d'évadés, les Marrons de Jamaïque entre autres, ont tenu leur propre territoire pendant des générations. Le Brésil a reçu plus de captifs que tout autre pays et a été le dernier des Amériques à abolir l'esclavage. Les profits de la traite ont bâti des ports et des banques en Europe, et son souvenir est une route de départ, une porte du Non-Retour et un débat sur ce qui reste dû."
  },
  18: {
    en: "In a few decades, European armies conquered almost the whole continent. Borders were drawn in Berlin in 1884 and 1885, with no African in the room. Resistance was immediate and often heroic: Samori Toure in the west, the Maji Maji rising in the east, the Herero and Nama in the south. Ethiopia alone won its war, at Adwa in 1896. And as empire spread, so did the idea that Africans should govern Africa. Every conquest met resistance, and the strongest did not always last the longest: some peoples fought the columns on the battlefield, others refused the tax, deserted the plantations, joined the new churches or carried messages for the movements that came later. The colonisers drew the borders they wanted, ruled through appointed chiefs, and laid railways from the mines and the plantations down to the sea. The land was taken, families were moved, and the schools taught the language of the conqueror. Ethiopia, which had won at Adwa, entered the twentieth century as the one country in Africa governed by its own rulers, until Italy occupied it from 1936 to 1941.",
    fr: "En quelques décennies, les armées européennes ont conquis presque tout le continent. Les frontières ont été tracées à Berlin en 1884 et 1885, sans aucun Africain dans la salle. La résistance a été immédiate et souvent héroïque : Samori Touré à l'ouest, la révolte des Maji Maji à l'est, les Herero et les Nama au sud. Seule l'Éthiopie a gagné sa guerre, à Adoua en 1896. Et à mesure que l'empire avançait, l'idée que les Africains devaient gouverner l'Afrique se répandait. Chaque conquête a rencontré une résistance, et la plus forte n'était pas toujours celle qui durait le plus longtemps : certains peuples ont affronté les colonnes sur le champ de bataille, d'autres ont refusé l'impôt, déserté les plantations, rejoint les nouvelles Églises ou porté les messages des mouvements venus plus tard. Les colonisateurs ont tracé les frontières qu'ils voulaient, gouverné par des chefs nommés et bâti des chemins de fer des mines et des plantations jusqu'à la mer. La terre a été prise, des familles déplacées, et les écoles ont enseigné la langue du vainqueur. L'Éthiopie, victorieuse à Adoua, est entrée dans le XXe siècle comme le seul pays d'Afrique gouverné par ses propres souverains, jusqu'à l'occupation italienne de 1936 à 1941."
  },
  19: {
    en: "In 1948, South Africa turned racial separation into the law of the land. Families were moved, passes were checked, schools were split. The answer came from Sharpeville in 1960 to Soweto in 1976, from the prison cells of Robben Island to the words of Steve Biko. After decades of struggle and world pressure, Nelson Mandela walked free in 1990, and in 1994 South Africans of every colour voted in the same election. The law had divided people into groups and given each group its own quarter, its own schools and its own future, and millions were moved to make the map fit the rule. Against it stood the ANC and its allies, the Pan Africanist Congress, the Black Consciousness movement, the churches and, from 1985, the trade unions of COSATU. Much of the world refused to trade or to play sport with South Africa. After 1994 the Truth and Reconciliation Commission heard the victims and the perpetrators, exchanging a full account of a crime for amnesty, and the country is still working out what it owes.",
    fr: "En 1948, l'Afrique du Sud a fait de la séparation raciale la loi du pays. Des familles ont été déplacées, les passes étaient contrôlées, les écoles séparées. La réponse est venue de Sharpeville en 1960 à Soweto en 1976, des cellules de Robben Island aux paroles de Steve Biko. Après des décennies de lutte et de pressions internationales, Nelson Mandela est sorti libre en 1990, et en 1994 les Sud-Africains de toutes les couleurs ont voté lors de la même élection. La loi divisait les gens par groupes et donnait à chaque groupe son quartier, ses écoles et son avenir, et des millions de personnes ont été déplacées pour que la carte corresponde à la règle. Face à elle se tenaient l'ANC et ses alliés, le Congrès panafricaniste, le mouvement de conscience noire, les Églises et, à partir de 1985, les syndicats réunis dans la COSATU. Une grande partie du monde a refusé de commercer ou de jouer contre l'Afrique du Sud. Après 1994, la Commission de la vérité et de la réconciliation a entendu les victimes et les auteurs des crimes, échangeant le récit complet d'un crime contre l'amnistie, et le pays cherche encore ce qu'il doit."
  },
  20: {
    en: "Africa today is the continent of the African Union and of the largest free trade area in the world by number of countries. It is where mobile money was invented, where a quarter of the world's people will live by 2050, and where the median age is nineteen. Fifty-four states belong to the African Union, and the free trade area agreed in 2018 began to be applied in 2021, which makes it the largest in the world by number of countries. The continent holds the world's largest reserves of cobalt and much of its platinum, and it is building the dams, the railways and the ports that it was not allowed to build for itself. It is also a continent of hard problems, from the wars of the Sahel to a warming climate, from the shrinking of Lake Chad to the debt that weighs on young economies. The history of Africa is not finished. It is being written now.",
    fr: "L'Afrique d'aujourd'hui, c'est le continent de l'Union africaine et de la plus grande zone de libre-échange du monde par le nombre de pays. C'est là que l'argent mobile a été inventé, là où vivra un quart de l'humanité en 2050, et où l'âge médian est de dix-neuf ans. Cinquante-quatre États appartiennent à l'Union africaine, et la zone de libre-échange conclue en 2018 a commencé à s'appliquer en 2021 : c'est la plus grande du monde par le nombre de pays. Le continent détient les plus grandes réserves mondiales de cobalt et une grande partie du platine, et il construit les barrages, les chemins de fer et les ports qu'on ne l'a pas laissé bâtir pour lui-même. C'est aussi un continent aux problèmes difficiles, des guerres du Sahel au réchauffement climatique, du recul du lac Tchad à la dette qui pèse sur des économies jeunes. L'histoire de l'Afrique n'est pas terminée : elle s'écrit maintenant."
  },
  21: {
    en: "The Amazigh, who call themselves Imazighen, have lived across North Africa since long before Carthage or Rome. Their king Masinissa united Numidia, and his grandson Jugurtha fought Rome for years, while Numidian horsemen rode without saddle or bridle. Augustine was born at Thagaste and became bishop of Hippo, and Septimius Severus, born at Leptis Magna, ruled Rome itself. When the Arab armies came, Dihya al-Kahina led the resistance in the Aures, and in time Amazigh dynasties, the Almoravids and the Almohads, ruled the Maghreb from Marrakesh. The mountains kept the languages alive, and the Tuareg still write them in the Tifinagh script.",
    fr: "Les Amazighs, qui se nomment Imazighen, vivent en Afrique du Nord bien avant Carthage et Rome. Leur roi Massinissa a unifié la Numidie, et son petit-fils Jugurtha a combattu Rome pendant des années, tandis que les cavaliers numides montaient sans selle ni bride. Augustin est né à Thagaste et est devenu évêque d'Hippone, et Septime Sévère, né à Leptis Magna, a régné sur Rome. Quand les armées arabes sont arrivées, Dihya al-Kahina a conduit la résistance dans les Aurès, puis des dynasties amazighes, les Almoravides et les Almohades, ont régné sur le Maghreb depuis Marrakech. Les montagnes ont gardé les langues vivantes, et les Touaregs les écrivent encore en tifinagh."
  },
  22: {
    en: "Madagascar was settled around 500 AD by sailors from the Indonesian archipelago, who crossed the Indian Ocean in outrigger canoes and brought their language with them. Farmers from the mainland followed with cattle, and the highlands filled with rice fields while the zebu became the measure of a family's wealth. The Merina kingdom united the highlands under Andrianampoinimerina, and his son Radama I opened the island to European trade, before Ranavalona I closed it again. France invaded in 1895 and made the island a colony until 1960. The lemur and the baobab live nowhere else, and families still gather for the famadihana to wrap their ancestors in new cloth.",
    fr: "Madagascar a été peuplée vers 500 apr. J.-C. par des marins de l'archipel indonésien, qui ont traversé l'océan Indien en pirogue à balancier et ont apporté leur langue. Des agriculteurs du continent ont suivi avec le bétail, et les hauts plateaux se sont couverts de rizières tandis que le zébu devenait la mesure de la richesse d'une famille. Le royaume mérina a unifié les hauts plateaux sous Andrianampoinimerina, et son fils Radama Ier a ouvert l'île au commerce européen avant que Ranavalona Ire ne la referme. La France a envahi l'île en 1895 et en a fait une colonie jusqu'en 1960. Le lémurien et le baobab ne vivent nulle part ailleurs, et les familles se réunissent encore pour le famadihana."
  },
  23: {
    en: "Between the great lakes of East Africa, a group of kingdoms grew up after the year 1000. Bunyoro-Kitara looked back to the Bachwezi, and Buganda, Rwanda, Burundi and Karagwe took their own shape between the water and the highlands. Cattle and bananas were the base of the economy, and herds were lent in return for service. The kabaka of Buganda ruled with his clans and a fleet of canoes, and by the nineteenth century his kingdom was the strongest of the region. Arab and Swahili caravans brought cloth, beads and firearms from the coast and carried away ivory and captives. German and then Belgian rule followed, and the kingdoms survived in new forms.",
    fr: "Entre les grands lacs d'Afrique de l'Est, plusieurs royaumes se sont formés après l'an 1000. Le Bunyoro-Kitara se réclamait des Bachwezi, et le Buganda, le Rwanda, le Burundi et le Karagwe ont pris forme entre l'eau et les hauts plateaux. Le bétail et la banane étaient la base de l'économie, et les troupeaux étaient prêtés en échange de services. Le kabaka du Buganda gouvernait avec ses clans et une flotte de pirogues, et au XIXe siècle son royaume était le plus fort de la région. Les caravanes arabes et swahilies apportaient tissus, perles et armes à feu et remportaient ivoire et captifs. La domination allemande, puis belge, a suivi, et les royaumes ont survécu sous de nouvelles formes."
  },
  24: {
    en: "In 1482 a Portuguese fleet reached the mouth of the Congo, and Portuguese envoys soon stood at the court of the kingdom of Kongo, where Afonso I wrote to Lisbon as an equal. South along the coast the Portuguese founded Luanda in 1575 and built Angola on the trade of captives, while the island of Mozambique became the seat of Portuguese East Africa and Fort Jesus guarded the route to India. They held Guinea-Bissau and settled Cape Verde and Sao Tome, and along the Zambezi the prazos were granted to settlers. Portugal kept its colonies longer than the other empires, and after the fall of its dictatorship in 1974 they became independent in 1975.",
    fr: "En 1482, une flotte portugaise a atteint l'embouchure du Congo, et des envoyés portugais se sont bientôt tenus à la cour du royaume du Kongo, où Afonso Ier écrivait à Lisbonne d'égal à égal. Plus au sud, les Portugais ont fondé Luanda en 1575 et bâti l'Angola sur le commerce des captifs, tandis que l'île de Mozambique devenait le siège de l'Afrique orientale portugaise et que Fort Jesus gardait la route des Indes. Ils ont gardé la Guinée-Bissau et peuplé le Cap-Vert et Sao Tome, et le long du Zambèze les prazos étaient accordés aux colons. Le Portugal a gardé ses colonies plus longtemps que les autres empires, et après la chute de sa dictature en 1974, elles sont devenues indépendantes en 1975."
  },
  25: {
    en: "In the forests of what is now Ghana, the Akan peoples were organised in small states when Osei Tutu and his priest Okomfo Anokye united them around 1700. The Golden Stool, said to have come down from the sky, stood for the whole nation rather than for the king, and Kumasi became the capital of a kingdom that grew on gold and kola. Britain held forts on the coast and fought a series of wars with Asante, burning Kumasi in 1874 and exiling Prempeh I in 1896. In 1900 the queen mother Yaa Asantewaa led the last war against a governor who demanded the Golden Stool. The kingdom joined the independent Ghana in 1957.",
    fr: "Dans les forêts de l'actuel Ghana, les peuples akan étaient organisés en petits États quand Osei Tutu et son prêtre Okomfo Anokye les ont unis vers 1700. Le Tabouret d'or, dit descendu du ciel, représentait la nation entière plutôt que le roi, et Kumasi est devenue la capitale d'un royaume enrichi par l'or et la kola. La Grande-Bretagne tenait des forts sur la côte et a mené une série de guerres contre l'Asante, brûlant Kumasi en 1874 et exilant Prempeh Ier en 1896. En 1900, la reine mère Yaa Asantewaa a conduit la dernière guerre contre un gouverneur qui exigeait le Tabouret d'or. Le royaume a rejoint le Ghana indépendant en 1957."
  },
  26: {
    en: "In the Hausa cities of the Sahel, a scholar named Usman dan Fodio taught and wrote for years before 1804, when he left Gobir and called his followers to reform. The movement became the Sokoto Caliphate, the largest state in nineteenth century Africa, with Sokoto as its capital and Muhammad Bello ruling the east while Abdullahi governed the west from Gwandu. The emirates judged by the sharia, Kano sent its blue cloth across the Sahara, and Nana Asma'u taught women and wrote in three languages. In 1903 a British force under Frederick Lugard took Sokoto and ended the caliphate, but the sultan and the emirs survive in northern Nigeria.",
    fr: "Dans les cités haoussa du Sahel, un savant nommé Usman dan Fodio a enseigné et écrit pendant des années avant 1804, quand il a quitté le Gobir et appelé ses partisans à la réforme. Le mouvement est devenu le califat de Sokoto, le plus grand État de l'Afrique du XIXe siècle, avec Sokoto pour capitale, Muhammad Bello gouvernant l'est et Abdullahi l'ouest depuis Gwandu. Les émirats jugeaient selon la charia, Kano envoyait son tissu bleu à travers le Sahara, et Nana Asma'u enseignait aux femmes et écrivait en trois langues. En 1903, une force britannique commandée par Frederick Lugard a pris Sokoto et mis fin au califat, mais le sultan et les émirs subsistent dans le nord du Nigeria."
  }
};

export function getLevelStory(levelId, lang) {
  return LEVEL_STORIES[levelId]?.[lang] || LEVEL_STORIES[levelId]?.en || "";
}

export default function AudioNarrator({ levelId }) {
  const t = useT();
  const [state, setState] = useState("idle"); // idle | playing | paused | loading | unsupported
  const utteranceRef = useRef(null);
  const lang = useLang();

  const story = LEVEL_STORIES[levelId]?.[lang] || LEVEL_STORIES[levelId]?.en;

  useEffect(() => {
    return () => {
      if (window.speechSynthesis) window.speechSynthesis.cancel();
    };
  }, []);

  if (!story) return null;
  if (typeof window === "undefined" || !window.speechSynthesis) return null;

  const handlePlay = () => {
    const synth = window.speechSynthesis;

    if (state === "playing") {
      synth.pause();
      setState("paused");
      return;
    }

    if (state === "paused") {
      synth.resume();
      setState("playing");
      return;
    }

    // Fresh start
    synth.cancel();
    setState("loading");

    const utterance = new SpeechSynthesisUtterance(story);
    utterance.lang = lang === "fr" ? "fr-FR" : "en-US";
    utterance.rate = 0.9;
    utterance.pitch = 1.05;

    // Try to pick a nice voice
    const voices = synth.getVoices();
    const preferred = voices.find(v =>
      v.lang.startsWith(lang === "fr" ? "fr" : "en") && !v.name.includes("Google")
    ) || voices.find(v => v.lang.startsWith(lang === "fr" ? "fr" : "en"));
    if (preferred) utterance.voice = preferred;

    utterance.onstart = () => setState("playing");
    utterance.onend = () => setState("idle");
    utterance.onerror = () => setState("idle");

    utteranceRef.current = utterance;
    synth.speak(utterance);
  };

  const handleStop = () => {
    window.speechSynthesis.cancel();
    setState("idle");
  };

  const isActive = state === "playing" || state === "paused";

  return (
    <div
      className="bg-gradient-to-r from-amber-50 to-orange-50 border border-amber-200 rounded-2xl p-4 mb-6 flex items-start gap-3"
    >
      <div className="flex flex-col gap-1 flex-1">
        <p className="flex items-center gap-1.5 text-xs font-bold text-amber-700 uppercase tracking-widest">
          <Mic className="w-3.5 h-3.5" aria-hidden="true" />
          {lang === "fr" ? "Écouter l'histoire" : "Listen to the story"}
        </p>
        <p className="text-xs text-slate-600 leading-relaxed line-clamp-2">{story.substring(0, 80)}…</p>
      </div>

      <div className="flex items-center gap-2 shrink-0">
        {isActive && (
          <button
            onClick={handleStop}
            aria-label={t.stopAudio}
            className="p-3 rounded-xl bg-white border border-slate-300 hover:bg-slate-50 transition-colors"
          >
            <VolumeX className="w-4 h-4 text-slate-600" aria-hidden="true" />
          </button>
        )}
        <button
          onClick={handlePlay}
          className={`flex items-center gap-2 min-h-11 px-3 py-2 rounded-xl font-bold text-sm transition-all ${
            state === "playing"
              ? "bg-orange-700 text-white shadow-md shadow-orange-200"
              : "bg-amber-700 text-white hover:bg-amber-800 shadow-md shadow-amber-200"
          }`}
        >
          {state === "loading" ? (
            <Loader2 className="w-4 h-4 animate-spin" />
          ) : state === "playing" ? (
            <Pause className="w-4 h-4" />
          ) : (
            <Play className="w-4 h-4" />
          )}
          {state === "playing"
            ? (lang === "fr" ? "Pause" : "Pause")
            : state === "paused"
            ? (lang === "fr" ? "Reprendre" : "Resume")
            : (lang === "fr" ? "Écouter" : "Listen")}
        </button>
      </div>
    </div>
  );
}