/**
 * The brief of the game: the twenty levels as the first screen needs them.
 *
 * WRITTEN BY scripts/generate-level-facts.mjs. Do not edit by hand: the facts
 * below are read out of the level table, the French wording and the photograph
 * table, and `npm run verify` regenerates them and fails when this file no
 * longer matches those three. Run `npm run level:facts` after changing one of
 * them.
 *
 * Everything a level card draws is here, and nothing else is: the title and its
 * place in the timeline in both languages, the icon and the colour, the picture
 * on the card, and how many questions the level holds. The questions themselves,
 * the lesson stories and the rest of the gallery stay out of the entry file, so
 * a player waiting for the map is not made to download the whole game for it.
 */

export const LEVEL_FACTS = [
  {
    id: 1,
    order: 2,
    era: "ancient",
    from: -3100,
    title: "Ancient Egypt",
    subtitle: "Land of the Pharaohs",
    region: "North Africa",
    color: "from-amber-400 to-yellow-500",
    icon: "Landmark",
    image: "/photos/level-1-1.jpg",
    questionCount: 13,
    fr: { title: "Égypte antique", subtitle: "Terre des pharaons", region: "Afrique du Nord" },
  },
  {
    id: 2,
    order: 3,
    era: "ancient",
    from: -1070,
    title: "Kingdom of Kush",
    subtitle: "Nubia's Golden Empire",
    region: "Northeast Africa",
    color: "from-amber-600 to-orange-800",
    icon: "Crown",
    image: "/photos/level-2-1.jpg",
    questionCount: 13,
    fr: { title: "Royaume de Kouch", subtitle: "L'empire doré de Nubie", region: "Afrique du Nord-Est" },
  },
  {
    id: 3,
    order: 10,
    era: "medieval",
    from: 1100,
    title: "Great Zimbabwe",
    subtitle: "City of Stone",
    region: "Southern Africa",
    color: "from-emerald-400 to-green-600",
    icon: "Castle",
    image: "/photos/level-3-1.jpg",
    questionCount: 13,
    fr: { title: "Grand Zimbabwe", subtitle: "La cité de pierre", region: "Afrique australe" },
  },
  {
    id: 4,
    order: 12,
    era: "medieval",
    from: 1235,
    title: "Mali Empire",
    subtitle: "Mansa Musa's Golden Age",
    region: "West Africa",
    color: "from-yellow-500 to-orange-500",
    icon: "Coins",
    image: "/photos/level-4-1.jpg",
    questionCount: 13,
    fr: { title: "Empire du Mali", subtitle: "L'âge d'or de Mansa Moussa", region: "Afrique de l'Ouest" },
  },
  {
    id: 5,
    order: 6,
    era: "ancient",
    from: 100,
    title: "Kingdom of Axum",
    subtitle: "Ethiopia's Ancient Power",
    region: "East Africa",
    color: "from-red-500 to-orange-600",
    icon: "Church",
    image: "/photos/level-5-1.jpg",
    questionCount: 13,
    fr: { title: "Royaume d'Axoum", subtitle: "La puissance antique d'Éthiopie", region: "Afrique de l'Est" },
  },
  {
    id: 6,
    order: 14,
    era: "medieval",
    from: 1464,
    title: "Songhai Empire",
    subtitle: "Africa's Largest Empire",
    region: "West Africa",
    color: "from-teal-400 to-cyan-600",
    icon: "Swords",
    image: "/photos/level-6-1.jpg",
    questionCount: 13,
    fr: { title: "Empire songhaï", subtitle: "Le plus grand empire d'Afrique", region: "Afrique de l'Ouest" },
  },
  {
    id: 7,
    order: 16,
    era: "modern",
    from: 1816,
    title: "Zulu Kingdom",
    subtitle: "Warriors of the South",
    region: "Southern Africa",
    color: "from-orange-400 to-red-500",
    icon: "Shield",
    image: "/photos/level-7-1.jpg",
    questionCount: 13,
    fr: { title: "Royaume zoulou", subtitle: "Les guerriers du Sud", region: "Afrique australe" },
  },
  {
    id: 8,
    order: 19,
    era: "contemporary",
    from: 1951,
    title: "African Independence",
    subtitle: "Freedom Across the Continent",
    region: "All of Africa",
    color: "from-green-500 to-emerald-600",
    icon: "Flag",
    image: "/photos/level-8-1.jpg",
    questionCount: 13,
    fr: { title: "Indépendances africaines", subtitle: "La liberté sur tout le continent", region: "Toute l'Afrique" },
  },
  {
    id: 9,
    order: 1,
    era: "origins",
    from: -300000,
    title: "Human Origins",
    subtitle: "Africa, cradle of humankind",
    region: "Whole of Africa",
    color: "from-stone-500 to-amber-800",
    icon: "Footprints",
    image: "/photos/level-9-1.jpg",
    questionCount: 8,
    fr: { title: "Les origines de l'humanité", subtitle: "L'Afrique, berceau de l'humanité", region: "Toute l'Afrique" },
  },
  {
    id: 10,
    order: 5,
    era: "ancient",
    from: -814,
    title: "Carthage and Ancient North Africa",
    subtitle: "Rome's rival across the sea",
    region: "North Africa",
    color: "from-sky-500 to-blue-700",
    icon: "Anchor",
    image: "/photos/level-10-1.jpg",
    questionCount: 8,
    fr: { title: "Carthage et l'Afrique du Nord antique", subtitle: "La rivale de Rome", region: "Afrique du Nord" },
  },
  {
    id: 11,
    order: 4,
    era: "ancient",
    from: -1000,
    title: "The Iron Age",
    subtitle: "Nok terracottas and the Bantu expansion",
    region: "Central and Southern Africa",
    color: "from-orange-700 to-red-800",
    icon: "Hammer",
    image: "/photos/level-11-1.jpg",
    questionCount: 8,
    fr: { title: "L'âge du fer", subtitle: "Terres cuites nok et expansion bantoue", region: "Afrique centrale et australe" },
  },
  {
    id: 12,
    order: 11,
    era: "medieval",
    from: 1137,
    title: "Medieval Ethiopia",
    subtitle: "Lalibela and the Solomonic dynasty",
    region: "Horn of Africa",
    color: "from-yellow-600 to-red-700",
    icon: "Mountain",
    image: "/photos/level-12-1.jpg",
    questionCount: 8,
    fr: { title: "L'Éthiopie médiévale", subtitle: "Lalibela et la dynastie salomonide", region: "Corne de l'Afrique" },
  },
  {
    id: 13,
    order: 7,
    era: "medieval",
    from: 700,
    title: "The Ghana Empire",
    subtitle: "Wagadu, land of gold",
    region: "West Africa",
    color: "from-yellow-400 to-amber-600",
    icon: "Gem",
    image: "/photos/level-13-1.jpg",
    questionCount: 8,
    fr: { title: "L'empire du Ghana", subtitle: "Wagadu, pays de l'or", region: "Afrique de l'Ouest" },
  },
  {
    id: 14,
    order: 8,
    era: "medieval",
    from: 800,
    title: "Kanem-Bornu and the Hausa Cities",
    subtitle: "Riders, scholars and city walls",
    region: "Central Sahel",
    color: "from-lime-600 to-emerald-800",
    icon: "Scroll",
    image: "/photos/level-14-1.jpg",
    questionCount: 8,
    fr: { title: "Kanem-Bornou et les cités haoussa", subtitle: "Cavaliers, savants et remparts", region: "Sahel central" },
  },
  {
    id: 15,
    order: 9,
    era: "medieval",
    from: 900,
    title: "The Swahili Coast",
    subtitle: "Kilwa, Zanzibar and the monsoon trade",
    region: "East African coast",
    color: "from-cyan-500 to-teal-700",
    icon: "Ship",
    image: "/photos/level-15-1.jpg",
    questionCount: 8,
    fr: { title: "La côte swahili", subtitle: "Kilwa, Zanzibar et le commerce de mousson", region: "Côte est-africaine" },
  },
  {
    id: 16,
    order: 13,
    era: "medieval",
    from: 1390,
    title: "Forest Kingdoms",
    subtitle: "Kongo, Benin, Ife and Oyo",
    region: "Central and West Africa",
    color: "from-green-600 to-emerald-800",
    icon: "Building2",
    image: "/photos/level-16-1.jpg",
    questionCount: 8,
    fr: { title: "Les royaumes de la forêt", subtitle: "Kongo, Bénin, Ifé et Oyo", region: "Afrique centrale et de l'Ouest" },
  },
  {
    id: 17,
    order: 15,
    era: "earlyModern",
    from: 1500,
    title: "The Atlantic Slave Trade",
    subtitle: "Exile, resistance and abolition",
    region: "Atlantic Africa",
    color: "from-slate-500 to-slate-800",
    icon: "Globe",
    image: "/photos/level-17-1.jpg",
    questionCount: 8,
    fr: { title: "La traite atlantique", subtitle: "Exil, résistance et abolition", region: "Afrique atlantique" },
  },
  {
    id: 18,
    order: 17,
    era: "modern",
    from: 1884,
    title: "Colonial Conquest",
    subtitle: "Resistance, Adwa and pan-Africanism",
    region: "Across the continent",
    color: "from-rose-600 to-red-900",
    icon: "Map",
    image: "/photos/level-18-1.jpg",
    questionCount: 8,
    fr: { title: "La conquête coloniale", subtitle: "Résistances, Adoua et panafricanisme", region: "Sur tout le continent" },
  },
  {
    id: 19,
    order: 18,
    era: "contemporary",
    from: 1948,
    title: "Apartheid",
    subtitle: "The long road to freedom in South Africa",
    region: "Southern Africa",
    color: "from-amber-700 to-stone-800",
    icon: "Scale",
    image: "/photos/level-19-1.jpg",
    questionCount: 8,
    fr: { title: "L'apartheid", subtitle: "La longue marche vers la liberté en Afrique du Sud", region: "Afrique australe" },
  },
  {
    id: 20,
    order: 20,
    era: "contemporary",
    from: 1990,
    title: "Africa Today",
    subtitle: "Union, growth and new challenges",
    region: "Across the continent",
    color: "from-teal-500 to-green-700",
    icon: "Rocket",
    image: "/photos/level-20-1.jpg",
    questionCount: 8,
    fr: { title: "L'Afrique d'aujourd'hui", subtitle: "Union, croissance et nouveaux défis", region: "Sur tout le continent" },
  },
];

/**
 * The photographs that also ship an AVIF, in the order of the table.
 *
 * The third format is a fact about the files, recorded as a fingerprint by
 * scripts/stamp-photos.mjs, and a browser cannot ask for a picture and fall back
 * when it is not there: a picture without one is offered as WebP alone, which is
 * what this list says.
 */
export const AVIF_FILES = [
  "/photos/level-1-2.jpg",
  "/photos/level-1-3.jpg",
  "/photos/level-2-2.jpg",
  "/photos/level-3-2.jpg",
  "/photos/level-3-3.jpg",
  "/photos/level-4-2.jpg",
  "/photos/level-5-2.jpg",
  "/photos/level-5-3.jpg",
  "/photos/level-6-2.jpg",
  "/photos/level-7-1.jpg",
  "/photos/level-7-2.jpg",
  "/photos/level-7-3.jpg",
  "/photos/level-8-3.jpg",
  "/photos/level-9-2.jpg",
  "/photos/level-10-2.jpg",
  "/photos/level-10-3.jpg",
  "/photos/level-12-2.jpg",
  "/photos/level-13-1.jpg",
  "/photos/level-13-2.jpg",
  "/photos/level-13-3.jpg",
  "/photos/level-14-3.jpg",
  "/photos/level-15-2.jpg",
  "/photos/level-15-3.jpg",
  "/photos/level-16-3.jpg",
  "/photos/level-17-2.jpg",
  "/photos/level-17-3.jpg",
  "/photos/level-18-3.jpg",
  "/photos/level-20-2.jpg",
];
